version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: container_nginx
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    volumes:
      - ../:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx

  php:
    image: php:7.2.20-fpm
    container_name: container_php
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/logs:/usr/local/var/log
      - ../:/usr/share/nginx/html
    external_links:
      - nginx:docker.localhost
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G

  memcached:
    image: memcached
    container_name: container_memcached
    ports:
      - 11211:11211
    expose:
      - 11211

  redis:
    image: redis
    container_name: container_redis
    ports:
      - 6379:6379
    expose:
      - 6379

  mysql:
    image: mysql:5.7
    container_name: container_mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: app
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: container_phpmyadmin
    ports:
      - 8001:80
    expose:
      - 8001
    volumes:
      - ./phpmyadmin/php-fpm.conf:/etc/php-fpm.conf
      - ./phpmyadmin/nginx.conf:/etc/nginx.conf
      - ./phpmyadmin/php.ini:/etc/php.ini
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 12345
    restart: always
